name: PhantomTools
main: videogamesm12.phantomtools.PhantomTools
version: ${project.version}
description: A recreation of the VideoCraftPlugin that I started working on when I was 11.
authors: [VideoGameSmash12, cowgomooo12]
commands:
    dialup:
        usage: /dialup
        description: A reference to an online service that many people used to use.
    
    notchtroll:
        usage: /notchtroll
        description: In PhantomToolsPlus (a modified version of PhantomTools), this was one of the few commands that it featured.
        
    colors:
        usage: /colors
        description: Lists all of the colors possible in Minecraft.
        aliases: colours
    
    phantomtools:
        usage: /phantomtools
        description: Provides some details about PhantomTools. Still under construction.
