name: PhantomTools
main: com.phantomoediv215.phantomtools.PhantomTools
version: 0.2
description: The return of the VideoCraftPlugin, now remastered! Includes some joke commands.
author: PhantomOediv215
commands:
    dialup:
        usage: /<command>
        description: Joke command number 1.
    
    notchtroll:
        usage: /<command>
        description: This command is useless, but I just added it just for the heck of it. On the VideoFreedom server, this is blocked to only Super Admins.
    
    rocket:
        usage: /rocket
        description: Get a rocket and shoot things!
    