name: PhantomTools
main: com.phantomoediv215.phantomtools.PhantomTools
version: 0.2.1
description: Recreation of the VideoCraftPlugin.
authors: [VideoGameSmash12, cowgomooo12]
commands:
    dialup:
        usage: /dialup
        description: A reference to an online service that many people used to use.
    
    notchtroll:
        usage: /notchtroll
        description: In PhantomToolsPlus (a modified version of PhantomTools), this was one of the few commands that it featured.
    
    rocket:
        usage: /rocket
        description: Rockets don't exist.
        
    colors:
        usage: /colors
        description: Lists all of the colors possible in Minecraft.
        aliases: colours
    
    phantomtools:
        usage: /phantomtools
        description: Provides some details about PhantomTools. Still under construction.